# Site settings
title: Rock Paper Dynamite
email: rpd@cerberos.id.au
description: > # this means to ignore newlines until "baseurl:"
	The sporadic ramblings of someone who enjoys playing Magic the Gathering, 
	eating good and bad food and exploring what it means to be a Christian in 
	my communities.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lovestha
#github_username:  lovestha

# Build settings
markdown: kramdown
